myblog/myblog/urls.py
from django.contrib import admin
from django.urls import path,include
# from .settings import DEBUG, STATIC_URL, STATICFILES_DIRS , MEDIA_URL, MEDIA_ROOT
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myblog_app.urls')),
    path('members/', include('django.contrib.auth.urls')),
    path('members/', include('members.urls')),
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

# if DEBUG:
    # urlpatterns += static(STATIC_URL,document_root =STATICFILES_DIRS )
    # urlpatterns += static(MEDIA_URL,document_root = MEDIA_ROOT)

myblog/myblog_app/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import HomeView,ArticleDetailView,AddPostView,UpdatePostView,DeletePostView,AddCategoryView,CategoryView,CategoryListView,LikeView,AddCommentView,Posts

urlpatterns = [
    # path('', HomeView.as_view(),name='home'),
    path('', login_required(HomeView.as_view(),login_url='/members/login/'),name='home'),
    path('posts/', Posts.as_view(), name='posts'),
    path('article/<int:pk>', ArticleDetailView.as_view(),name='article-detail'),
    path('add_post/', AddPostView.as_view(),name='add_post'),
    path('article/edit/<int:pk>', UpdatePostView.as_view(),name='update_post'),
    path('article/<int:pk>/comment/', AddCommentView.as_view(),name='add_comment'),
    path('article/<int:pk>/remove', DeletePostView.as_view(),name='delete_post'),
    path('add_category/', AddCategoryView.as_view(),name='add_category'),
    path('category/<str:cats>/', CategoryView,name='category'),
    path('category-list/', CategoryListView,name='category_list'),
    path('like/<int:pk>', LikeView,name='like_post'),
]

myblog/myblog_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from ckeditor.fields import RichTextField
from django.utils.translation import gettext_lazy as _
from datetime import datetime,date

class Category(models.Model):
    class Meta:
        verbose_name = _('Category')
        verbose_name_plural = _('Categories')
        ordering = ['id']

    name=models.CharField(max_length=255,verbose_name=_('Category'))

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category')

class Profile(models.Model):
    class Meta:
        verbose_name = _('Profile')
        verbose_name_plural = _('Profiles')
        ordering = ['id']

    user=models.OneToOneField(User,null=True,on_delete=models.CASCADE,verbose_name=_('User'))
    profile_pic= models.ImageField(null=True,blank=True,upload_to='images/profile/',verbose_name=_('Profile Picture'))
    bio=models.TextField(null=True,blank=True,verbose_name=_('Bio'))

    def __str__(self):
        return str(self.user)


class Post(models.Model):
    class Meta:
        verbose_name = _('Post')
        verbose_name_plural = _('Posts')
        ordering = ['id']

    title= models.CharField(max_length=255,verbose_name=_('Post Title'))
    header_image= models.ImageField(null=True,blank=True,upload_to='images/',verbose_name=_('Image'))
    author=models.ForeignKey(User,on_delete=models.CASCADE,verbose_name=_('Author'))
    body=RichTextField(blank=True,null=True,verbose_name=_('Description'))
    status = models.BooleanField(default=False,verbose_name=_('Private'))
    post_date=models.DateTimeField(auto_now_add=True,verbose_name=_('Date Posted'))
    category= models.CharField(max_length=255,verbose_name=_('Category'))
    likes= models.ManyToManyField(User,related_name='blog_posts',verbose_name=_('Likes'))

    def total_likes(self):
        return self.likes.count()

    def __str__(self):
        return '%s | %s' % (self.title, self.author)

    def get_absolute_url(self):
        # return reverse('article-details',args=(str(self.id)))
        return reverse('home')

class Comment(models.Model):
    class Meta:
        verbose_name = _('Comment')
        verbose_name_plural = _('Comments')
        ordering = ['id']

    post=models.ForeignKey(Post,related_name='comments',on_delete=models.CASCADE,verbose_name=_('Post Comment'))
    name=models.CharField(max_length=255,verbose_name=_('Correspondent'))
    body=models.TextField(verbose_name=_('Comment'))
    date_added=models.DateTimeField(auto_now_add=True,verbose_name=_('Date Commented'))

    def __str__(self):
        return '%s - %s' % (self.post.title, self.name)

myblog/myblog_app/forms.py
from django import forms
from .models import Post,Category,Comment

choices=Category.objects.all().values_list('name','name')

choice_list=[]

for item in choices:
    choice_list.append(item)

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title','author','body','category','header_image','status')

        widgets= {
            # 'title':forms.TextInput(attrs={'class':'form-control','placeholder':'This is a placeholder'}),
            'title':forms.TextInput(attrs={'class':'form-control'}),
            'author':forms.TextInput(attrs={'class':'form-control','value':'','id':'author_id','type':'hidden'}),
            'category':forms.Select(choices=choice_list,attrs={'class':'form-control'}),
            'status':forms.CheckboxInput(attrs={'class':'form-check-input'}),
            'body':forms.Textarea(attrs={'class':'form-control'}),
        }

class EditForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title','body','category','status','header_image')

        widgets= {
            'title':forms.TextInput(attrs={'class':'form-control'}),
            'body':forms.Textarea(attrs={'class':'form-control'}),
            'category': forms.Select(choices=choices, attrs={'class': 'form-select'}),
            'status': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name','body')

        widgets= {
            'name':forms.TextInput(attrs={'class':'form-control'}),
            'body':forms.Textarea(attrs={'class':'form-control'}),
        }

myblog/myblog_app/views.py
from django.shortcuts import render,get_object_or_404
from django.views.generic import ListView,DetailView,CreateView,UpdateView,DeleteView
from .models import Post,Category,Comment
from .forms import PostForm,EditForm,CommentForm
from django.urls import reverse_lazy,reverse
from django.http import HttpResponseRedirect


def LikeView(request,pk):
    post=get_object_or_404(Post,id=request.POST.get('post_id'))
    liked = False
    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
        liked = False
    else:
        post.likes.add(request.user)
        liked = True
    return HttpResponseRedirect(reverse('article-detail', args=[str(pk)]),liked)

class HomeView(ListView):
    model = Post
    template_name='home.html'
    cats= Category.objects.all()
    ordering = ['-post_date']

    def get_context_data(self,*args , **kwargs):
        cat_menu = Category.objects.all()
        context=super(HomeView,self).get_context_data(*args,**kwargs)
        context['cat_menu']=cat_menu
        return context

def CategoryView(request,cats):
    category_posts=Post.objects.filter(category=cats.title().replace('-',' '),post_date__isnull=False).order_by('-post_date')
    return render(request,'categories.html',{'cats':cats.title().replace('-',' '),'category_posts':category_posts})

def CategoryListView(request):
    cat_menu_list = Category.objects.all()
    return render(request,'categories_list.html',{'cat_menu_list':cat_menu_list})

class ArticleDetailView(DetailView):
    model = Post
    template_name='article_details.html'

    def get_context_data(self,*args , **kwargs):
        cat_menu = Category.objects.all()
        context=super(ArticleDetailView,self).get_context_data(*args,**kwargs)

        post=get_object_or_404(Post,id=self.kwargs['pk'])
        total_likes=post.total_likes()

        liked = False
        if post.likes.filter(id=self.request.user.id).exists():
            liked = True

        context['cat_menu'] = cat_menu
        context['total_likes'] = total_likes
        context['liked'] = liked
        return context


class AddPostView(CreateView):
    model = Post
    form_class = PostForm
    template_name = 'add_post.html'

    # fields='__all__'
    # fields=['title','body']

    # def form_valid(self, form):
    #     form.instance.user=self.request.user
    #     return super().form_valid(form)

class AddCommentView(CreateView):
    model = Comment
    form_class = CommentForm
    template_name = 'add_comment.html'

    success_url = reverse_lazy('home')
    # fields='__all__'
    def form_valid(self, form):
        form.instance.post_id = self.kwargs['pk']
        return super().form_valid(form)

class AddCategoryView(CreateView):
    model = Category
    template_name = 'add_category.html'
    fields = '__all__'
    success_url = reverse_lazy('category_list')

class UpdatePostView(UpdateView):
    model= Post
    form_class = EditForm
    template_name='update_post.html'
    # fields=['title','body','category','status','header_image']

class DeletePostView(DeleteView):
    model = Post
    template_name = 'delete_post.html'
    success_url = reverse_lazy('home')

class Posts(ListView):
    model = Post
    template_name = 'posts.html'
    cats = Category.objects.all()
    ordering = ['-post_date']

    def get_context_data(self, *args, **kwargs):
        cat_menu = Category.objects.all()
        post = Post.objects.all()
        context = super(Posts, self).get_context_data(*args, **kwargs)
        context['cat_menu'] = cat_menu
        context['post'] = post
        return context

myblog/myblog_app/templates/add_category.html
{% extends 'base.html' %}
{% block title %} Register {% endblock %}
{% block style %}{% load static %}
    <link href={% static "myblog_app/css/signin.css" %} rel="stylesheet"> {% endblock %}
{% block content %}
    <div class="form-group">
        <main class="form-signin">
            <div class="form-group">
                <form method="POST">
                    {% csrf_token %}
                    <h1 class="h2 mb-3 fw-normal">Add Category</h1>
                    <div class="form-floating">
                        <input type="text" class="form-control" id="id_name" placeholder="Category" name="name">
                        <label for="floatingInput">Category</label>
                    </div>
                    <br><br>
                    <button class="w-100 btn btn-lg btn-primary" type="submit">Add</button>
                </form>
            </div>
            <br>
            <a href="{% url 'category_list' %}" class="w-100 btn btn-lg btn-primary">Cancel</a>
        </main>
    </div>
{% endblock %}

myblog/myblog_app/templates/add_comment.html
{% if user.is_authenticated %}
    <h1>Comment on Post</h1>
    <div class="form-group">
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button>Add Comment</button>
        </form>
    </div>
{% else %}
    <h1>Page Not Found</h1>
{% endif %}

myblog/myblog_app/templates/add_post.html
{% extends 'base.html' %}
{% block style %}
    {% load static %}
    <link href={% static "myblog_app/css/signin.css" %} rel="stylesheet">
{% endblock %}
{% block title %}Add Post{% endblock %}
{% block content %}
    {% if user.is_authenticated %}
        <br><br>
        <div class="form-group">
        <main class="form-signin">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <h1 class="h3 mb-3 fw-normal">Create Post</h1>
            <hr>
            <br>
            {{ form.as_p }}
{#            <div class="form-floating">#}
{#                <input type="text" name="title" class="form-control" maxlength="255" required id="id_title">#}
{#                <label for="id_title">Title</label>#}
{#            </div>#}
{#            <br>#}
{#            <br>#}
{#            <p class="text-start">Upload an image</p>#}
{#            <input class="form-control form-control-sm" type="file" name="header_image" accept="image/*"#}
{#                   id="header_image" placeholder="Upload Image">#}
{#            <br>#}
{#            <div class="form-floating">#}
{#                <textarea class="form-control" style="height: 200px;max-height:200px;min-height: 200px " cols="40"#}
{#                          id="id_body" name="body" rows="10" data-processed="0"#}
{#                          data-config="{&quot;skin&quot;: &quot;moono-lisa&quot;, &quot;toolbar_Basic&quot;: [[&quot;Source&quot;, &quot;-&quot;, &quot;Bold&quot;, &quot;Italic&quot;]], &quot;toolbar_Full&quot;: [[&quot;Styles&quot;, &quot;Format&quot;, &quot;Bold&quot;, &quot;Italic&quot;, &quot;Underline&quot;, &quot;Strike&quot;, &quot;SpellChecker&quot;, &quot;Undo&quot;, &quot;Redo&quot;], [&quot;Link&quot;, &quot;Unlink&quot;, &quot;Anchor&quot;], [&quot;Image&quot;, &quot;Flash&quot;, &quot;Table&quot;, &quot;HorizontalRule&quot;], [&quot;TextColor&quot;, &quot;BGColor&quot;], [&quot;Smiley&quot;, &quot;SpecialChar&quot;], [&quot;Source&quot;]], &quot;toolbar&quot;: &quot;Full&quot;, &quot;height&quot;: 291, &quot;width&quot;: 835, &quot;filebrowserWindowWidth&quot;: 940, &quot;filebrowserWindowHeight&quot;: 725, &quot;language&quot;: &quot;en-us&quot;}"#}
{#                          data-external-plugin-resources="[]" data-id="id_body" data-type="ckeditortype"></textarea>#}
{#                <label for="id_body">Description</label>#}
{#            </div>#}
{#            <br>#}
{#            <select name="category" id="id_category" value="{{ form.category }}"></select>#}
{#            <br>#}
{#            <div class="checkbox mb-3">#}
{#                <p class="text-start">#}
{#                    <input type="checkbox" value="remember-me" id="id_status" class="form-check-input"> <label#}
{#                        for="id_status">Private</label>#}
{#                </p>#}
{#            </div>#}
            <br>
            <br>
            <button class="w-100 btn btn-lg btn-primary" type="submit">Post</button>
        </form>

        <script>
            var name = '{{ user.id }}'
            document.getElementById('author_id').value = name;
        </script>

    {% else %}
        <h1>Page Not Found</h1>
    {% endif %}
<br>
<a href="{% url 'home' %}" class="w-100 btn btn-lg btn-primary">Cancel</a>
</main>
</div>
{% endblock %}

myblog/myblog_app/templates/article_details.html
{% extends 'base.html' %}
{% block title %} Post {% endblock %}
{% load static %}
{% block content %}
    {% block center %}
        class="container" align="center"
    {% endblock %}
    <br><br>
    <br><br>
    <br>
    <div class="card text-center  mt-5 pt-5 card text-dark bg-light mb-3 shadow p-3 mb-5 bg-body rounded"
         style="width: 40rem;">
        <h1>{{ post.title|title }}</h1>
        <h6 class="card-subtitle mb-2 text-muted">
            <a href="{% url 'profile_page' post.author.profile.id %}"
               style="text-decoration: none">
                {% if post.author.profile.profile_pic %}
                    <img
                            class="rounded-circle shadow-sm p-1 mb-2 bg-body rounded"
                            src="{{ post.author.profile.profile_pic.url }}"
                            width="20" height="20"
                            alt="Profile Picture">
                {% else %}
                    <img
                            class="rounded-circle shadow-sm p-1 mb-2 bg-body rounded"
                            src="{% static 'myblog_app/images/user.png' %}"
                            width="20" height="20"
                            alt="Profile Picture">
                {% endif %}
                {{ post.author.username }}
            </a>

            | {{ post.post_date|date:"M d, Y" }}
            at {{ post.post_date|date:"P" }}</h6>
        <small>-{{ post.category }}-</small>
        {% if user.is_authenticated %}
            {% if user.id == post.author.id %}
                <small>
                    <a href="{% url 'update_post' post.pk %}">(Edit)</a>
                    <a href="{% url 'delete_post' post.pk %}">(Delete)</a>
                </small>
            {% endif %}
        {% endif %}
        <br>
        <hr>
        <h5>{{ post.body|safe }}</h5>
        <br>
        <br>
        {% if post.header_image %}
            <img src="{{ post.header_image.url }}" alt="image">
        {% endif %}
        <br>
        <hr>
        <br>
        <p class="text-start ms-3 ps-3">{{ post.total_likes }} <img
                src="{% static 'myblog_app/images/like.png' %}" width="20" height="20"> Likes</p>
        {% if user.is_authenticated %}
            <form action="{% url 'like_post' post.pk %}" method="POST">
                {% csrf_token %}
                {% if liked %}
                    <button type="submit" name="post_id" value="{{ post.id }}" class="btn btn-danger">
                        <img src="{% static 'myblog_app/images/dislike.png' %}" width="30" height="30" alt="Unlike">
                        Unlike
                    </button>
                    <br>
                {% else %}
                    <button type="submit" name="post_id" value="{{ post.id }}" class="btn btn-primary"><img
                            src="{% static 'myblog_app/images/like.png' %}" width="30" height="30" alt="Like"> Like
                    </button>
                    <br>
                {% endif %}
                <br>
            </form>
        {% else %}

            <small><a href="{% url 'login' %}">Login</a>to Like and Comment on Post</small>
            <br>
            <h2>Comments</h2>
            <br>
            {% if post.comments %}
                {% for comment in post.comments.all %}
                    <strong>
                        {{ comment.name }}
                        {{ comment.date_added }}
                    </strong>
                    <br>
                    {{ comment.body }}
                    <br>
                {% endfor %}
                <hr>
            {% endif %}

        {% endif %}
        <br>
        <br>
        <a href="add_comment" class="btn btn-primary">Add Comment</a>
    </div>
{% endblock %}

myblog/myblog_app/templates/base(copy).html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
{#    <meta name="generator" content="Hugo 0.83.1">#}
{#    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">#}

    <!-- Bootstrap CSS -->

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <!-- Favicons -->
    <link rel="icon" type="image/png" href="{% static 'myblog_app/images/logo.png' %}">

    <meta name="theme-color" content="#7952b3">


    <style>

    </style>


    <!-- Custom styles for this template -->
    <title>{% block title %}FishBook{% endblock %}</title>
    {#    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/sign-in/">#}
    {% block style %} {% endblock %}
</head>

<body class="text-center">
<div class="container">
    <br>
    {% block content %}

    {% endblock %}
</div>
<nav class="navbar fixed-top navbar-expand-sm navbar navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand ps-5" href="{% url 'home' %}"><img src="{% static 'myblog_app/images/logo.png' %}"
                                                                  width="60"
                                                                  height="60" class="d-inline-block align-left ">
            <h3>FishBook</h3>
        </a>
        {#        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll"#}
        {#                aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">#}
        {#            <span class="navbar-toggler-icon">Test</span>#}
        {#        </button>#}
{#        <div class="collapse navbar-collapse" id="navbarScroll">#}
{#            <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">#}
                <li class="nav-item">
                    <a href="{% url 'home' %}" role="button">
                        <img
                            src="{% static 'myblog_app/images/home.png' %}"
                            width="40" height="40"
                            alt="Home">
                    </a>
                </li>
                {#                        <li class="nav-item">#}
                {#                            <a class="nav-link" href="#">Link</a>#}
                {#                        </li>#}
{#            </ul>#}
{#        </div>#}
{#        <div class="d-flex">#}
            {% if user.is_authenticated %}
                <ul class="navbar-nav ml-auto my-4 my-lg-1 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
                    <li class="nav-item dropdown dropstart pe-5">
                        <a class="nav-link dropdown-toggle " href="#" id="navbarScrollingDropdown" role="button"
                           data-bs-toggle="dropdown" aria-expanded="True"> <b>{{ user.username|capfirst }}</b> <img
                                class="rounded-circle shadow-sm p-1 mb-2 bg-body rounded"
                                src="{% static 'myblog_app/images/user.png' %}"
                                width="40" height="40"
                                alt="Profile Picture">
                        </a>
                        <ul class="dropdown-menu dropdown-menu-dropstart " aria-labelledby="navbarScrollingDropdown">
                            <li>
                                <a class="dropdown-item " href="{% url 'edit_profile' %}">
                                    <img class="rounded-circle shadow-sm p-1 mb-2 bg-body rounded"
                                         src="{% static 'myblog_app/images/user.png' %}"
                                         width="40" height="40"
                                         alt="Profile Picture"> <b>{{ user.username|capfirst }}</b>
                                    <br>
                                    <small>See Your Profile</small>
                                </a>
                            </li>
                            <li>
                                <hr class="dropdown-divider">
                                <a class="dropdown-item" href="{% url 'edit_profile' %}">Settings</a>
                            </li>
                            <li>
                                <hr class="dropdown-divider">
                                <a class="dropdown-item" href="{% url 'posts' %}">My Posts</a>
                            </li>
                            {% if user.is_superuser %}
                                <li>
                                    <hr class="dropdown-divider">
                                    <a class="dropdown-item" href="{% url 'category_list' %}">Categories</a>
                                </li>
                            {% endif %}
                            <li>
                                <hr class="dropdown-divider">
                                <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            {% else %}
                <ul class="navbar-nav ml-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
                    <li><a class="nav-link active" href="{% url 'register' %}">Register</a></li>
                    <li class="nav-link active">|</li>
                    <li class="pe-5"><a class="nav-link active" href="{% url 'login' %}">Login</a></li>
                </ul>

            {% endif %}
        </div>
{#    </div>#}
</nav>
<br>



<!-- Optional JavaScript; choose one of the two! -->

<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
        crossorigin="anonymous"></script>

<!-- Option 2: Separate Popper and Bootstrap JS -->
<!--
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
-->
</body>
</html>

myblog/myblog_app/templates/categories_list.html
{% extends 'base.html' %}
{% block style %}
    {% load static %}
    <link href={% static "myblog_app/css/signin.css" %} rel="stylesheet">
{% endblock %}
{% block title %}Categories{% endblock %}
{% block content %}
    <div class="form-group">
        <main class="form-signin">
            <h1 class="h2 mb-3 fw-normal">Categories</h1>
            <hr>
            <br>
            {% for item in cat_menu_list %}
                <h4><a href="{% url 'category' item|slugify %}">{{ item }}</a></h4>
            {% endfor %}
            <br>
            {% if user.is_superuser %}
                <hr>
                <a class="w-100 btn btn-lg btn-primary" href="{% url 'add_category' %}">Add Category</a>
            {% endif %}
        </main>
    </div>
{% endblock %}

myblog/myblog_app/templates/delete_post.html
{% extends 'base.html' %}
{% block style %}
    {% load static %}
    <link href={% static "myblog_app/css/signin.css" %} rel="stylesheet">
{% endblock %}
{% block title %}Delete Post{% endblock %}
{% block content %}
    {% if user.is_authenticated %}
        {% if user.id == post.author.id %}
            <h1>Delete Post</h1>
            <h3>{{ post.title }}</h3>
            <br>
            <div class="form-group">
            <main class="form-signin">
            <form method="POST">
                {% csrf_token %}
                <strong>Are you sure?!</strong>
                <br><br>
                <button class="w-100 btn btn-lg btn-primary" type="submit">Delete Post!</button>
            </form>
            <br>
            <a href="{% url 'home' %}" class="w-100 btn btn-lg btn-primary">Cancel</a>
        {% endif %}
    {% else %}
        <h1>Page Not Found</h1>
    {% endif %}
</main>
</div>
{% endblock %}

myblog/myblog_app/templates/update_post.html
{% extends 'base.html' %}
{% block style %}
    {% load static %}
    <link href={% static "myblog_app/css/signin.css" %} rel="stylesheet">
{% endblock %}
{% block title %}Update Post{% endblock %}
{% block content %}


    {% if user.is_authenticated %}
        {% if user.id == post.author.id %}
            <br><br>
            <div class="form-group">
            <main class="form-signin">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <h1 class="h3 mb-3 fw-normal">Update Post</h1>
                <hr>
                <br>
                {{ form.as_p }}
{#                <div class="form-floating">#}
{#                    <input type="text" name="title" class="form-control" maxlength="255" required id="title">#}
{#                    <label for="floatingInput">Title</label>#}
{#                </div>#}
{#                <br>#}
{#                <br>#}
{#                <p class="text-start">Upload an image</p>#}
{#                <input class="form-control form-control-sm" type="file" name="header_image" accept="image/*"#}
{#                       id="header_image" placeholder="Upload Image">#}
{#                <br>#}
{#                <div class="form-floating">#}
{#                <textarea class="form-control" style="height: 200px;max-height:200px;min-height: 200px " cols="40"#}
{#                          id="body" name="body" rows="10" data-processed="0"#}
{#                          data-config="{&quot;skin&quot;: &quot;moono-lisa&quot;, &quot;toolbar_Basic&quot;: [[&quot;Source&quot;, &quot;-&quot;, &quot;Bold&quot;, &quot;Italic&quot;]], &quot;toolbar_Full&quot;: [[&quot;Styles&quot;, &quot;Format&quot;, &quot;Bold&quot;, &quot;Italic&quot;, &quot;Underline&quot;, &quot;Strike&quot;, &quot;SpellChecker&quot;, &quot;Undo&quot;, &quot;Redo&quot;], [&quot;Link&quot;, &quot;Unlink&quot;, &quot;Anchor&quot;], [&quot;Image&quot;, &quot;Flash&quot;, &quot;Table&quot;, &quot;HorizontalRule&quot;], [&quot;TextColor&quot;, &quot;BGColor&quot;], [&quot;Smiley&quot;, &quot;SpecialChar&quot;], [&quot;Source&quot;]], &quot;toolbar&quot;: &quot;Full&quot;, &quot;height&quot;: 291, &quot;width&quot;: 835, &quot;filebrowserWindowWidth&quot;: 940, &quot;filebrowserWindowHeight&quot;: 725, &quot;language&quot;: &quot;en-us&quot;}"#}
{#                          data-external-plugin-resources="[]" data-id="id_body" data-type="ckeditortype"></textarea>#}
{#                    <label for="floatingInput">Description</label>#}
{#                </div>#}
{#                <br>#}
{#                {{ form.category }}#}
{#                <br>#}
{#                <div class="checkbox mb-3">#}
{#                    <p class="text-start">#}
{#                        <input type="checkbox" value="remember-me" id="status" class="form-check-input"> Private#}
{#                    </p>#}
{#                </div>#}
                <br>
                <br>
                <button class="w-100 btn btn-lg btn-primary" type="submit">Update</button>
            </form>
            <br>
            <a href="{% url 'home' %}" class="w-100 btn btn-lg btn-primary">Cancel</a>
        {% endif %}
    {% else %}
        <h1>Page Not Found</h1>
    {% endif %}
</main>
</div>
{% endblock %}